minha_app/urls.py
# coding: utf-8

from django.urls import path
from . import views
from .views import ErrorPage

urlpatterns = [
    path('', views.index, name='index',),
    path('home/', views.home, name='home'),
    path('materiais/', views.indexMaterials, name='materials.index'),
    path('materiais/c/', views.createMaterials, name='materials.create'),
    path('materiais/e/<int:pk>/', views.editMaterials, name='materials.edit'),
    path('materiais/d/<int:pk>/', views.deleteMaterials, name='materials.delete'),
    path('emprestimos/', views.indexLoans, name='loans.index'),
    path('emprestimos/c/', views.createLoans, name='loans.create'),
    path('emprestimos/e/<int:pk>/', views.editLoans, name='loans.edit'),
    path('emprestimos/d/<int:pk>/', views.deleteLoans, name='loans.delete'),
    path('emprestimos/<str:beneficiary>', views.historyLoansByUser, name='loans.history_by_user'),
    
    path(r'^error_page/$', ErrorPage.as_view(), name="error-page"),

]

mon_mat_esp/urls.py
from django.contrib import admin
from django.urls import path, include
urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'accounts/', include('django.contrib.auth.urls')),
    path('', include('minha_app.urls'), name='minha_app'),
    path('', include('social_django.urls'), name='social'),
]

minha_app/models.py
from django.db import models
from datetime import datetime  

# Create your models here.
class Material(models.Model):
    name = models.CharField(max_length=300)
    qnt = models.IntegerField()
    qnt_available = models.IntegerField()
    def __str__(self):
        return self.name

class Loan(models.Model):
    beneficiary = models.CharField(max_length=300)
    material = models.ForeignKey(Material, on_delete=models.CASCADE)
    responsible = models.CharField(max_length=300)    
    loaned_date = models.DateTimeField(default=datetime.now, blank=True)
    returned = models.BooleanField(default=False)
    returned_date = models.DateTimeField(blank=True, null=True)
    

minha_app/forms.py
from django.utils.translation import gettext_lazy as _
from django import forms
from .models import *

class MaterialForm(forms.ModelForm):
    class Meta:
        model = Material
        fields = ['name', 'qnt']
        labels = {
            'name': _('Nome'),
            'qnt': _('Quantidade'),
        }

class LoanForm(forms.ModelForm):
    class Meta:
        model = Loan
        fields = ['beneficiary', 'material', 'loaned_date', 'returned', 'returned_date']
        labels = {
            'beneficiary': _('Beneficiado'),
            'material': _('Material'),
            'loaned_date': _('Data do empréstimo'),
            'returned': _('Devolvido?'),
            'returned_date': _('Data de devolução')
        }
        widgets = {
            'loaned_date': forms.DateInput(
                attrs={
                    'autocomplete': 'off'
                },
            ),
            'returned_date': forms.DateInput(
                attrs={
                    'autocomplete': 'off'
                },
            )
        }

minha_app/views.py
# coding: utf-8

from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from .models import Material, Loan
from .forms import MaterialForm, LoanForm

from django.views.generic.base import TemplateView

def index(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect(settings.LOGIN_REDIRECT_URL)
    return render(request, 'login.html', {})

def home(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect('/')
    return render(request, 'home.html', {})

def indexMaterials(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect('/')
    materials = Material.objects.all()
    return render(request, 'materials/index.html', { 'materials': materials })

def createMaterials(request):
    form = MaterialForm(request.POST or None)
    if form.is_valid():
        form.instance.qnt_available = form.cleaned_data['qnt']
        form.save()
        return redirect('materials.index')
    return render(request,'materials/create.html', {'form':form})

def editMaterials(request, pk):
    material = Material.objects.get(pk=pk)
    form = MaterialForm(request.POST or None, instance=material)
    if form.is_valid():
        form.save()
        return redirect('materials.index')
    return render(request,'materials/edit.html', {'form':form, 'material': material})

def deleteMaterials(request, pk):
    material = Material.objects.get(pk=pk)
    material.delete()
    return redirect('materials.index')

def indexLoans(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect('/')
    loans = Loan.objects.all()
    return render(request, 'loans/index.html', { 'loans': loans })

def createLoans(request):
    form = LoanForm(request.POST or None)
    if form.is_valid():
        form.instance.responsible = request.user.get_full_name() + ' (' + request.user.username + ')'
        material = Material.objects.get(pk=form.cleaned_data['material'].pk)
        if material.qnt_available > 0:
            form.save()
        return redirect('loans.index')
    return render(request,'loans/create.html', {'form':form})

def editLoans(request, pk):
    loan = Loan.objects.get(pk=pk)
    form = LoanForm(request.POST or None, instance=loan)
    if form.is_valid():
        form.instance.responsible = request.user.get_full_name() + ' (' + request.user.username + ')'
        material = Material.objects.get(pk=form.cleaned_data['material'].pk)
        if (material.qnt_available == 0 and form.cleaned_data['returned']) or material.qnt_available > 0:
            form.save()
        return redirect('loans.index')
    return render(request,'loans/edit.html', {'form':form, 'loan': loan})

def deleteLoans(request, pk):
    loan = Loan.objects.get(pk=pk)    
    loan.delete()
    return redirect('loans.index')

def historyLoansByUser(request, beneficiary):
    if not request.user.is_authenticated:
        return HttpResponseRedirect('/')
    loans = Loan.objects.filter(beneficiary=beneficiary)

    return render(request, 'loans/history_by_user.html', { 'loans': loans, 'beneficiary': beneficiary })

class ErrorPage(TemplateView):
    template_name = 'error.html'

minha_app/templates/error.html
<!-- Inutilizado temporariamente -->
{% extends "layouts/base.html" %}
{% block content %}
<body>
    {% if messages %}
       <ul class="messages">
          {% for message in messages %}
              <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }} </li>
       {% endfor %}
       </ul>
   {% endif %}
</body>
{% endblock content%}

minha_app/templates/home.html
{% extends "layouts/base.html" %}
{% block content %}
<div class="container">
    <h2>Olá, {{ user.get_full_name }}!</h2>
    <strong>username:</strong> {{ user.username }}<br/>
    <strong>first name:</strong> {{ user.first_name }}<br/>
    <strong>last name:</strong> {{ user.last_name }}<br/>
    <strong>email:</strong> {{ user.email }}<br/>
    {% with extra_data=user.social_auth.get.extra_data %}
        {% for k, v in extra_data.items %}
            <strong>{{ k }}:</strong> {{ v }}<br/>
        {% endfor %}
    {% endwith %}
    <hr/>
    <a class="btn btn-danger" href="{% url 'logout' %}?next=/">Encerrar Sessão</a>
</div>
{% endblock content%}

minha_app/templates/layouts/base-simples.html
<!DOCTYPE html>
{% load static %}
<!--
* CoreUI - Free Bootstrap Admin Template
* @version v4.2.2
* @link https://coreui.io
* Copyright (c) 2022 creativeLabs Łukasz Holeczek
* Licensed under MIT (https://coreui.io/license)
-->
<html lang="pt-br">

<head>
    <base href="./">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <meta name="description" content="CoreUI - Open Source Bootstrap Admin Template">
    <meta name="author" content="Łukasz Holeczek">
    <meta name="keyword" content="Bootstrap,Admin,Template,Open,Source,jQuery,CSS,HTML,RWD,Dashboard">
    <title>Login - Monitorador de materiais esportivos</title>
    <link rel="icon" type="image/png" sizes="192x192" href="{% static 'assets/favicon/android-icon-192x192.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'assets/favicon/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="96x96" href="{% static 'assets/favicon/favicon-96x96.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'assets/favicon/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'assets/favicon/manifest.json' %}">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="{% static 'assets/favicon/ms-icon-144x144.png' %}">
    <meta name="theme-color" content="#ffffff">
    <!-- Vendors styles-->
    <link rel="stylesheet" href="{% static 'vendors/simplebar/css/simplebar.css' %}">
    <link rel="stylesheet" href="{% static 'css/vendors/simplebar.css' %}">
    <!-- Main styles for this application-->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="{% static 'css/examples.css' %}" rel="stylesheet">
    <!-- Global site tag (gtag.js) - Google Analytics-->
    <script async="" src="https://www.googletagmanager.com/gtag/js?id=UA-118965717-3"></script>
    <script>
        window.dataLayer = window.dataLayer || [];

        function gtag() {
            dataLayer.push(arguments);
        }
        gtag('js', new Date());
        // Shared ID
        gtag('config', 'UA-118965717-3');
        // Bootstrap ID
        gtag('config', 'UA-118965717-5');
    </script>
</head>

<body>
    <div class="bg-light min-vh-100 d-flex flex-row align-items-center">
        {% block content %} {% endblock content %}
    </div>
    <!-- CoreUI and necessary plugins-->
    <script src="{% static 'vendors/@coreui/coreui/js/coreui.bundle.min.js' %}"></script>
    <script src="{% static 'vendors/simplebar/js/simplebar.min.js' %}"></script>
    <script>
    </script>

</body>

</html>

minha_app/templates/layouts/base.html
<!DOCTYPE html>
{% load static %}
<html lang="pt-br">

<head>
    <base href="./">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <meta name="description" content="CoreUI - Open Source Bootstrap Admin Template">
    <meta name="author" content="Łukasz Holeczek">
    <meta name="keyword" content="Bootstrap,Admin,Template,Open,Source,jQuery,CSS,HTML,RWD,Dashboard">
    <title>Login - Monitorador de materiais esportivos</title>
    <link rel="icon" type="image/png" sizes="192x192" href="{% static 'assets/favicon/android-icon-192x192.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'assets/favicon/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="96x96" href="{% static 'assets/favicon/favicon-96x96.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'assets/favicon/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'assets/favicon/manifest.json' %}">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="{% static 'assets/favicon/ms-icon-144x144.png' %}">
    <meta name="theme-color" content="#ffffff">
    <!-- Vendors styles-->
    <link rel="stylesheet" href="{% static 'vendors/simplebar/css/simplebar.css' %}">
    <link rel="stylesheet" href="{% static 'css/vendors/simplebar.css' %}">
    <!-- Main styles for this application-->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="{% static 'css/examples.css' %}" rel="stylesheet">    
    {% block styles %}{% endblock %}
    <!-- Global site tag (gtag.js) - Google Analytics-->
    <script async="" src="https://www.googletagmanager.com/gtag/js?id=UA-118965717-3"></script>
    <script>
        window.dataLayer = window.dataLayer || [];

        function gtag() {
            dataLayer.push(arguments);
        }
        gtag('js', new Date());
        // Shared ID
        gtag('config', 'UA-118965717-3');
        // Bootstrap ID
        gtag('config', 'UA-118965717-5');
    </script>
    <!-- BootStrap Icons -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css">
</head>

<body>
    <div class="sidebar sidebar-dark sidebar-fixed" id="sidebar">
        <div class="sidebar-brand d-none d-md-flex">
            <a class="dropdown">
                <a class="nav-link py-0" data-coreui-toggle="dropdown" href="#"
                    role="button" aria-haspopup="true" aria-expanded="false">
                    <div class="avatar avatar-md"><img class="avatar-img"
                            src="{% static 'assets/img/avatars/8.jpg' %}" alt="{{ user.get_full_name }}"></div>
                    <span class="ms-2">{{ user.get_full_name }}</span>

                </a>
                <div class="dropdown-menu dropdown-menu-end pt-0">
                    <div class="dropdown-header bg-light py-2">
                        <div class="fw-semibold">Config.</div>
                        <a class="dropdown-item" href="{% url 'logout' %}?next=/">
                            <i class="bi bi-box-arrow-right"></i> Sair</a>
                    </div>
                </div>
            </a>
            
        </div>
        <ul class="sidebar-nav" data-coreui="navigation" data-simplebar="">
            <li class="nav-item"><a class="nav-link" href="{% url 'home' %}">
                <i class="bi bi-house me-2"></i> <span>Início</span></a>
            </li>
            <li class="nav-item"><a class="nav-link" href="{% url 'materials.index' %}">
                <i class="bi bi-archive me-2"></i> <span>Materiais</span></a>
            </li>
            <li class="nav-item"><a class="nav-link" href="{% url 'loans.index' %}">
                <i class="bi bi-upload me-2"></i> <span>Empréstimos</span></a>
            </li>
        </ul>
    </div>
    <div class="wrapper d-flex flex-column min-vh-100 bg-light">
        <header class="header header-sticky mb-4">
            <div class="container-fluid">
                <button class="header-toggler px-md-0 me-md-3" type="button"
                    onclick="coreui.Sidebar.getInstance(document.querySelector('#sidebar')).toggle()">
                    <i class="bi bi-list"></i>
                </button>

                <a class="header-brand d-md-none" href="#">
                    LOGO</a>
                <ul class="header-nav d-none d-md-flex me-auto">
                    <li class="nav-item"><a class="nav-link" href="{% url 'home' %}">Início</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'materials.index' %}">Materiais</a></li>                    
                    <li class="nav-item"><a class="nav-link" href="{% url 'loans.index' %}">Empréstimos</a></li>                    
                </ul>                
                
            </div>
            <div class="header-divider"></div>
            <div class="container-fluid">
                {% block content %}{% endblock content %}
            </div>
        </header>
        <div class="body flex-grow-1 px-3">
            <div class="container-lg">
            </div>
        </div>
        <footer class="footer">
            <div>Marlison Silva, Maxsuel Silva, Maria Fortaleza, Juan Araújo</a> © 2023 IFRN</div>
        </footer>
    </div>
    <!-- CoreUI and necessary plugins-->
    <script src="{% static 'vendors/@coreui/coreui/js/coreui.bundle.min.js' %}"></script>
    <script src="{% static 'vendors/simplebar/js/simplebar.min.js' %}"></script>
    {% block scripts %}{% endblock %}

</body>

</html>

minha_app/templates/loans/create.html
{% extends "layouts/base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block styles %}
    <link href="{% static 'assets/css/datepicker.min.css' %}" rel="stylesheet" type="text/css" />
    <style>
        button.btn.btn-outline-secondary {
            height: 100%;
        }
    </style>
{% endblock %}
{% block content %}
<!-- Container fluid  -->

<div class="container">
    <!-- RECENT SALES -->
    <div class="row">
        <div class="col-md-12 col-lg-12 col-sm-12">
            <div class="white-box">
                <h3>Novo empréstimo</h3>
                <form method="post" id="form">
                    {% csrf_token %}
                    {{ form | crispy }}
                    <button type="submit" class="btn btn-success mt-3" style="width: 100px;">Salvar</button>
                </form>
            </div>
        </div>
    </div>
</div>
<!-- End Container fluid  -->
{% endblock content %}
{% block scripts %}
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script src="{% static 'assets/js/datepicker.min.js' %}" type="text/javascript"></script>

<script>
    $('#id_returned_date').datepicker({
        uiLibrary: 'bootstrap4',
        format: 'dd/mm/yyyy'

    });
</script>
{% endblock %}

minha_app/templates/loans/edit.html
{% extends "layouts/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<!-- Container fluid  -->

<div class="container">
    <!-- RECENT SALES -->
    <div class="row">
        <div class="col-md-12 col-lg-12 col-sm-12">
            <div class="white-box">
                <h3>Editar empréstimo de {{ loan.beneficiary }}</h3>
                <form method="post" id="form">
                    {% csrf_token %}
                    {{ form | crispy }}

                    <button type="submit" class="btn btn-success mt-3" style="width: 100px;">Salvar</button>

                </form>
            </div>
        </div>
    </div>
</div>
<!-- End Container fluid  -->
{% endblock content %}

minha_app/templates/loans/history_by_user.html
{% extends "layouts/base.html" %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-8">
            <h2>Empréstimos realizados por {{ beneficiary }}</h2>
        </div>
        <div class="col-4 d-flex justify-content-end align-items-center">
            <a href="{% url 'loans.index' %}" class="btn btn-success">Lista completa</a>
        </div>
    </div>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Beneficiado</th>
                <th scope="col">Material</th>
                <th scope="col">Data de empréstimo</th>                
                <th scope="col">Devolvido?</th>
                <th scope="col">Data de devolução</th>                
                <th scope="col">Responsável</th>
                <th scope="col">Ação</th>
            </tr>
        </thead>
        <tbody>
            {% for loan in loans %}
            <tr>
                <th scope="row">{{ loan.id }}</th>
                <td>{{ loan.beneficiary }}</td>
                <td>{{ loan.material }}</td>
                <td>{{ loan.loaned_date | date:"d/m/Y" }}</td>
                {% if loan.returned %}
                    <td>Sim</td>
                    <td>{{ loan.returned_date | date:"d/m/Y" }}</td>

                {% else %}
                    <td>Não</td>
                    <td></td>
                {% endif %}
                <td>{{ loan.responsible }}</td>
                <td><a class="btn btn-sm btn-primary" href="{% url 'loans.edit' loan.id %}"><i class="bi bi-pencil"></i></a><a class="btn btn-sm btn-primary ms-1" href="{% url 'loans.delete' loan.id %}"><i class="bi bi-trash"></i></a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock content %}

minha_app/templates/loans/index.html
{% extends "layouts/base.html" %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-8">
            <h2>Empréstimos realizados</h2>
        </div>
        <div class="col-4 d-flex justify-content-end align-items-center">
            <a href="{% url 'loans.create' %}" class="btn btn-primary">Criar novo</a>
        </div>
    </div>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Beneficiado</th>
                <th scope="col">Material</th>
                <th scope="col">Data de empréstimo</th>                
                <th scope="col">Devolvido?</th>
                <th scope="col">Data de devolução</th>                
                <th scope="col">Responsável</th>
                <th scope="col">Ação</th>
            </tr>
        </thead>
        <tbody>
            {% for loan in loans %}
            <tr>
                <th scope="row">{{ loan.id }}</th>
                <td>{{ loan.beneficiary }}</td>
                <td>{{ loan.material }}</td>
                <td>{{ loan.loaned_date | date:"d/m/Y" }}</td>
                {% if loan.returned %}
                    <td>Sim</td>
                    <td>{{ loan.returned_date | date:"d/m/Y" }}</td>

                {% else %}
                    <td>Não</td>
                    <td></td>
                {% endif %}
                <td>{{ loan.responsible }}</td>
                <td><a class="btn btn-sm btn-primary" href="{% url 'loans.edit' loan.id %}"><i class="bi bi-pencil"></i></a><a class="btn btn-sm btn-primary ms-1" href="{% url 'loans.delete' loan.id %}"><i class="bi bi-trash"></i></a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock content %}

minha_app/templates/login.html
{% extends "layouts/base-simples.html" %}
{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-lg-6">
            <div class="card-group d-block d-md-flex">
                <div class="card p-4 mb-0" style="width: max(100%, 400px);">
                    <div class="card-body">
                        <h1>Login</h1>
                        <p class="text-medium-emphasis">Fazer login com o SUAP.</p>
                        <p>Ao clicar em "Entrar", você será redirecionado(a) para o SUAP, onde poderá ver os dados que
                            nos serão fornecidos.</p>
                        <div class="row">
                            <div class="col-6">
                                <a class="btn btn-success px-4"
                                    href="{% url 'social:begin' 'suap' %}">Entrar</a>
                            </div>
                            <div class="col-6 text-end">
                                <button class="btn btn-link px-0" type="button">Forgot password?</button>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>
{% endblock content %}

minha_app/templates/materials/create.html
{% extends "layouts/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<!-- Container fluid  -->

<div class="container">
    <!-- RECENT SALES -->
    <div class="row">
        <div class="col-md-12 col-lg-12 col-sm-12">
            <div class="white-box">
                <h3>Novo material esportivo</h3>
                <form method="post" id="form">
                    {% csrf_token %}
                    {{ form | crispy }}
                    <button type="submit" class="btn btn-success mt-3" style="width: 100px;">Salvar</button>
                </form>
            </div>
        </div>
    </div>
</div>
<!-- End Container fluid  -->
{% endblock content %}

minha_app/templates/materials/edit.html
{% extends "layouts/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<!-- Container fluid  -->

<div class="container">
    <!-- RECENT SALES -->
    <div class="row">
        <div class="col-md-12 col-lg-12 col-sm-12">
            <div class="white-box">
                <h3>Editar {{ material.name }}</h3>
                <form method="post" id="form">
                    {% csrf_token %}
                    {{ form | crispy }}

                    <button type="submit" class="btn btn-success mt-3" style="width: 100px;">Salvar</button>

                </form>
            </div>
        </div>
    </div>
</div>
<!-- End Container fluid  -->
{% endblock content %}

minha_app/templates/materials/index.html
{% extends "layouts/base.html" %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-8">
            <h2>Materiais esportivos cadastrados</h2>
        </div>
        <div class="col-4 d-flex justify-content-end align-items-center">
            <a href="{% url 'materials.create' %}" class="btn btn-success">Criar novo</a>
        </div>
    </div>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Nome</th>
                <th scope="col">Quantidade</th>
                <th scope="col">Quantidade disponível</th>
                <th scope="col">Ação</th>
            </tr>
        </thead>
        <tbody>
            {% for material in materials %}
            <tr>
                <th scope="row">{{ material.id }}</th>
                <td>{{ material.name }}</td>
                <td>{{ material.qnt }}</td>
                <td>{{ material.qnt_available }}</td>
                <td><a class="btn btn-sm btn-primary" href="{% url 'materials.edit' material.id %}"><i class="bi bi-pencil"></i></a><a class="btn btn-sm btn-primary ms-1" href="{% url 'materials.delete' material.id %}"><i class="bi bi-trash"></i></a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock content %}

minha_app/templates/profile.html
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Cliente SUAP Django</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.0/css/bulma.min.css">
  </head>
  <body>
		<section class="hero is-link is-bold">
	    <div class="hero-body">
	      <div class="container">
	        <h1 class="title">Cliente SUAP Django</h1>
	      </div>
	    </div>
	  </section>
  	<section class="section">
		  <div class="container">
	  		<div class="content">
            <h2>Olá, {{ user.get_full_name }}!</h2>
            <strong>username:</strong> {{ user.username }}<br/>
            <strong>first name:</strong> {{ user.first_name }}<br/>
            <strong>last name:</strong> {{ user.last_name }}<br/>
            <strong>email:</strong> {{ user.email }}<br/>
            {% with extra_data=user.social_auth.get.extra_data %}
                {% for k, v in extra_data.items %}
                    <strong>{{ k }}:</strong> {{ v }}<br/>
                {% endfor %}
            {% endwith %}
            <hr/>
            <a class="button is-danger is-large" href="{% url 'logout' %}?next=/">Encerrar Sessão</a>
		  	</div>
		  </div>
	  </section>
	</body>
</html>
<html>